export const login = "login"
export const newcategory = "newcategory"
export const LoadData = "loaddata"
export const removeCategory = "removecategory"
export const newProduct = "newproduct"
export const removeProduct = "removeproduct"
export const LoadData2 = "loaddata2"